name: 'migrations alert'
description: 'alert when deploying the migrations'
inputs:
  SLACK_WEBHOOK: 
    description: 'alert reciever'
    required: true
  ENVIRONMENT: 
    description: 'dev|prod'
  CHANGED_FILES:
    description: 'Recently changed files'
  HEADER_MSG:
    description: 'Alert message header'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 100
    - name: Migration alert
      id: migration-alert
      shell: bash
      run: |
        set -x
        msg="$HEADER"
        for file in ${FILES[@]}
          do
            if [[ -f "$file" && "$file" != *.test.ts ]]; then
              GIT_USER_NAME=$(git blame --line-porcelain "$file" | sed -n 's/^author //p' | sort | uniq -c | sort -rn | awk 'FNR == 1{ print $2}')
              slackname=$(bash .github/scripts/map_dev_names.sh "$GIT_USER_NAME") 
              filename=$(basename $file)
              msg+="Hey <@$slackname>, Kindly monitor the progress of the $filename migration. Thank you%0A"
            fi
        done
        echo "MESSAGE=${msg}" >> "$GITHUB_OUTPUT"
      env:
        FILES: ${{ inputs.CHANGED_FILES }}
        HEADER: ${{ inputs.HEADER_MSG }}
    - name: Slack notification
      if: inputs.CHANGED_FILES
      uses: rtCamp/action-slack-notify@v2.2.0
      env:
        SLACK_USERNAME: "Migrations"
        SLACK_WEBHOOK: ${{ inputs.SLACK_WEBHOOK }}
        SLACK_TITLE:  migrations-${{ inputs.ENVIRONMENT }}
        SLACK_MESSAGE: ${{ steps.migration-alert.outputs.MESSAGE }}
        SLACK_CHANNEL: "cd-status"
        SLACK_LINK_NAMES: "true"